# Generated by Django 6.0.5 on 2026-06-03 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('autor', models.CharField(default='Anónimo', max_length=150)),
                ('sinopsis', models.TextField()),
                ('portada', models.ImageField(upload_to='portadas_manga/')),
                ('estado', models.CharField(choices=[('emision', 'En Emisión'), ('finalizado', 'Finalizado'), ('pausa', 'En Pausa')], default='emision', max_length=20)),
                ('calificacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, max_length=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('generos', models.ManyToManyField(related_name='mangas', to='biblioteca.genero')),
            ],
        ),
    ]
