# Generated by Django 6.0.5 on 2026-06-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_capitulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulo',
            options={'ordering': ['tomo', '-numero'], 'verbose_name': 'Capítulo', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.AddField(
            model_name='capitulo',
            name='tomo',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Déjalo en blanco si es un capítulo semanal sin tomo oficial.', max_digits=5, null=True),
        ),
    ]
