# Generated by Django 6.0.5 on 2026-06-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_historiallectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiallectura',
            name='pagina_actual',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
